// Generated by Selenium IDE
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.Firefox;
using OpenQA.Selenium.Remote;
using OpenQA.Selenium.Support.UI;
using OpenQA.Selenium.Interactions;
using NUnit.Framework;
[TestFixture]
public class EjemploTest {
  private IWebDriver driver;
  public IDictionary<string, object> vars {get; private set;}
  private IJavaScriptExecutor js;
  [SetUp]
  public void SetUp() {
    driver = new ChromeDriver();
    js = (IJavaScriptExecutor)driver;
    vars = new Dictionary<string, object>();
  }
  [TearDown]
  protected void TearDown() {
    driver.Quit();
  }
  [Test]
  public void ejemplo() {
    driver.Navigate().GoToUrl("http://localhost/Hotel/index.php");
    driver.Manage().Window.Size = new System.Drawing.Size(697, 728);
    driver.FindElement(By.CssSelector(".fadeInDown")).Click();
    driver.FindElement(By.CssSelector(".navbar-toggle")).Click();
    driver.FindElement(By.LinkText("Rooms & Tariff")).Click();
    driver.FindElement(By.LinkText("Check Details")).Click();
    driver.FindElement(By.CssSelector(".col-sm-3:nth-child(3) span")).Click();
  }
}
